version: '3.9'
services:
  jellyhookapi:
    container_name: jellysookapi
    restart: always
    image: python:alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python jellysookapi.py"
    ports:
      - "0.0.0.0:7778:7778"
    networks:
      net-chill:
        ipv4_address: 10.10.66.198

networks:
  net-chill:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.66.0/24

